#!/bin/bash
echo "this version dont need mkdir its make mkdir automatically and dont need pre installed network manager and iwd and if dont work try repair if possible this script is only to use hyprland with less complication"
mkdir -p ~/.config/hypr ~/.config/kitty
sudo pacman -S --noconfirm swww waybar wofi wl-clipboard curl kitty pipewire pipewire-pulse intel-media-driver libva-intel-driver nvidia networkmanager iwd hyprland nvidia-prime

cat << 'EOF' > ~/.config/hypr/hyprland.conf
autogenerated = 0
monitor=,highrr,auto,1

env = LIBVA_DRIVER_NAME,intel
env = __GLX_VENDOR_LIBRARY_NAME,intel
env = WLR_NO_HARDWARE_CURSORS,1

$terminal = kitty
$menu = wofi --show drun

exec-once = swww-daemon
# exec-once = swww img
exec-once = waybar

general {
    gaps_in = 5
    gaps_out = 10
    border_size = 3
    col.active_border = rgb(009c3b) rgb(ffdf00) 45deg
    col.inactive_border = rgba(595959aa)
}

decoration {
    rounding = 10
    blur {
        enabled = true
        size = 3
    }
}

animations {
    enabled = true
    bezier = myBezier, 0.05, 0.9, 0.1, 1.05
    animation = windows, 1, 7, myBezier
    animation = windowsOut, 1, 7, default, popin 80%
    animation = border, 1, 10, default
    animation = fade, 1, 7, default
    animation = workspaces, 1, 6, default
}

bind = SUPER, Return, exec, $terminal
bind = SUPER SHIFT, Q, killactive,
bind = SUPER SHIFT, E, exit,
bind = SUPER, D, exec, $menu
bind = SUPER, left, movefocus, l
bind = SUPER, right, movefocus, r
bind = SUPER, up, movefocus, u
bind = SUPER, down, movefocus, d

input {
    kb_layout = br
    touchpad {
        natural_scroll = true
    }
}
EOF

cat << 'EOF' > ~/.config/kitty/kitty.conf
background_opacity 0.8
confirm_os_window_close 0
EOF

sudo mkdir -p /etc/NetworkManager/conf.d/
echo -e "[device]\nwifi.backend=iwd" | sudo tee /etc/NetworkManager/conf.d/wifi_backend.conf

curl -s 'https://liquorix.net/install-liquorix.sh' | sudo bash

sudo bash -c "cat << 'EOF' > /etc/modprobe.d/nvidia.conf
options nvidia-drm modeset=1
options nvidia NVreg_PreserveVideoMemoryAllocations=1
options nvidia NVreg_TemporaryFilePath=/var/tmp
options nvidia NVreg_DynamicPowerManagement=0x02
EOF"

sudo sed -i 's/MODULES=(\(.*\))/MODULES=(i915 nvidia nvidia_modeset nvidia_uvm nvidia_drm \1)/' /etc/mkinitcpio.conf
sudo mkinitcpio -P
sudo grub-mkconfig -o /boot/grub/grub.cfg

echo 'config installed you are finally a brazil patriot restarting the arch linux'
sudo systemctl enable iwd
sudo systemctl enable NetworkManager
sudo reboot
